version: "3.9"

services:
  jupyter-lab-playground:
    build:
      context: .docker/jupyter-lab
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8888:8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .docker/jupyter-lab/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
